"""add listing profit cost fields

Revision ID: 035912bc0b6f
Revises: 7d6b39669728
Create Date: 2026-09-02 16:50:24.914145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035912bc0b6f'
down_revision: Union[str, Sequence[str], None] = '7d6b39669728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etsy_listings', sa.Column('product_cost_usd', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('etsy_listings', sa.Column('actual_shipping_cost_usd', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('etsy_listings', sa.Column('supplier_source', sa.String(length=50), nullable=True))
    op.add_column('etsy_listings', sa.Column('supplier_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etsy_listings', 'supplier_url')
    op.drop_column('etsy_listings', 'supplier_source')
    op.drop_column('etsy_listings', 'actual_shipping_cost_usd')
    op.drop_column('etsy_listings', 'product_cost_usd')
    # ### end Alembic commands ###
