"""add password reset fields

Revision ID: 0e3492426058
Revises: 9b67fe3e8a06
Create Date: 2026-08-27 21:45:59.446844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3492426058'
down_revision: Union[str, Sequence[str], None] = '9b67fe3e8a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_token_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_token_expires')
    op.drop_column('users', 'password_reset_token_hash')
    # ### end Alembic commands ###
