"""add etsy listings

Revision ID: 70cbde9128ad
Revises: efc4485ea899
Create Date: 2026-08-28 17:48:39.424633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70cbde9128ad'
down_revision: Union[str, Sequence[str], None] = 'efc4485ea899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etsy_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.String(length=100), nullable=False),
    sa.Column('listing_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etsy_listings_id'), 'etsy_listings', ['id'], unique=False)
    op.create_index(op.f('ix_etsy_listings_listing_id'), 'etsy_listings', ['listing_id'], unique=True)
    op.create_index(op.f('ix_etsy_listings_shop_id'), 'etsy_listings', ['shop_id'], unique=False)
    op.create_index(op.f('ix_etsy_listings_user_id'), 'etsy_listings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etsy_listings_user_id'), table_name='etsy_listings')
    op.drop_index(op.f('ix_etsy_listings_shop_id'), table_name='etsy_listings')
    op.drop_index(op.f('ix_etsy_listings_listing_id'), table_name='etsy_listings')
    op.drop_index(op.f('ix_etsy_listings_id'), table_name='etsy_listings')
    op.drop_table('etsy_listings')
    # ### end Alembic commands ###
