"""add etsy connections

Revision ID: 744735297e26
Revises: 0e3492426058
Create Date: 2026-08-28 17:03:08.561247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744735297e26'
down_revision: Union[str, Sequence[str], None] = '0e3492426058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etsy_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('etsy_user_id', sa.String(length=100), nullable=True),
    sa.Column('shop_id', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etsy_connections_id'), 'etsy_connections', ['id'], unique=False)
    op.create_index(op.f('ix_etsy_connections_shop_id'), 'etsy_connections', ['shop_id'], unique=False)
    op.create_index(op.f('ix_etsy_connections_user_id'), 'etsy_connections', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etsy_connections_user_id'), table_name='etsy_connections')
    op.drop_index(op.f('ix_etsy_connections_shop_id'), table_name='etsy_connections')
    op.drop_index(op.f('ix_etsy_connections_id'), table_name='etsy_connections')
    op.drop_table('etsy_connections')
    # ### end Alembic commands ###
