"""add image fields to etsy listings

Revision ID: 7d6b39669728
Revises: 70cbde9128ad
Create Date: 2026-08-28 22:17:51.559896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6b39669728'
down_revision: Union[str, Sequence[str], None] = '70cbde9128ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "etsy_listings",
        sa.Column(
            "image_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "etsy_listings",
        sa.Column(
            "image_urls",
            sa.Text(),
            nullable=True,
        ),
    )

    op.alter_column(
        "etsy_listings",
        "image_count",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etsy_listings', 'image_urls')
    op.drop_column('etsy_listings', 'image_count')
    # ### end Alembic commands ###
