"""add etsy oauth states

Revision ID: efc4485ea899
Revises: 744735297e26
Create Date: 2026-08-28 17:38:52.730927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc4485ea899'
down_revision: Union[str, Sequence[str], None] = '744735297e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etsy_oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_verifier', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etsy_oauth_states_expires_at'), 'etsy_oauth_states', ['expires_at'], unique=False)
    op.create_index(op.f('ix_etsy_oauth_states_id'), 'etsy_oauth_states', ['id'], unique=False)
    op.create_index(op.f('ix_etsy_oauth_states_state'), 'etsy_oauth_states', ['state'], unique=True)
    op.create_index(op.f('ix_etsy_oauth_states_user_id'), 'etsy_oauth_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etsy_oauth_states_user_id'), table_name='etsy_oauth_states')
    op.drop_index(op.f('ix_etsy_oauth_states_state'), table_name='etsy_oauth_states')
    op.drop_index(op.f('ix_etsy_oauth_states_id'), table_name='etsy_oauth_states')
    op.drop_index(op.f('ix_etsy_oauth_states_expires_at'), table_name='etsy_oauth_states')
    op.drop_table('etsy_oauth_states')
    # ### end Alembic commands ###
